name: Cypress Tests
on: [push]
jobs:
 install:
   runs-on: ubuntu-latest

   steps:
    - uses: actions/checkout@v4
    - name: use node
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - run: npm install
    - run: npx cypress run --record --key 459b68f9-b69e-4f3d-8acb-5dae6c537925"
